stages:
  - lint
  - release

python-safety:
  stage: lint
  image: pipelinecomponents/python-safety:latest
  script:
    - safety check --full-report -r requirements.txt

pylint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/pylint:amd64-0b84da4
  before_script:
    - pip install -r requirements.txt
  script:
    - pylint --errors-only ffxiv.py

release:
  image: node:13
  stage: release
  only:
    refs:
    - main
    #- alpha
    # This matches maintenance branches
    #- /^(([0-9]+)\.)?([0-9]+)\.x/
    # This matches pre-releases
    #- /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
  script:
    - npm install @semantic-release/gitlab
    - npm install -g semantic-release @semantic-release/gitlab-config
    - npm install @semantic-release/changelog
    - npm install @semantic-release/release-notes-generator
    - npx semantic-release