python-safety:
  stage: test
  image: pipelinecomponents/python-safety:latest
  script:
    - safety check --full-report -r requirements.txt

pylint:
  stage: test
  image: registry.gitlab.com/pipeline-components/pylint:amd64-0b84da4
  script:
    - pylint **/*.py
